version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/public:/var/www/html           # Monta a pasta public como raiz do servidor
      - ./backend/src:/var/www/src               # Monta a pasta src para acesso aos includes
    ports:
      - "8000:80"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Expondo o Vue frontend na porta 3000
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contas_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  # Para persistência de dados

volumes:
  db_data:
