version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public:/var/www/html           # Monta a pasta public como raiz do servidor
      - ./src:/var/www/src               # Monta a pasta src para acesso aos includes
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contas_db
    ports:
      - "5432:5432"
